//! Unicode data for the engine, read from `unicode.bin` (generated by
//! `zig build ucdgen` from the Character Database, Unicode 17): code
//! point tables for general categories, scripts and script extensions,
//! the binary properties `\p{}` may name, the identifier classes the
//! lexer needs, simple case folding (`i` under `u`), and the simple and
//! full case mappings String's case conversions apply. Every lookup is
//! a binary search in the embedded blob; nothing is decoded ahead.
const std = @import("std");

const blob = @embedFile("unicode.bin");

pub const Range = extern struct { lo: u32, hi: u32 };

const dir_start = 8;
const entry_size = 40;

fn count() u32 {
    return std.mem.readInt(u32, blob[4..8], .little);
}

fn entryName(i: usize) []const u8 {
    const e = blob[dir_start + i * entry_size ..][0..32];
    const n = std.mem.indexOfScalar(u8, e, 0) orelse 32;
    return e[0..n];
}

const Entry = struct { offset: u32, n: u32 };

fn find(name: []const u8) ?Entry {
    var lo: usize = 0;
    var hi: usize = count();
    while (lo < hi) {
        const mid = (lo + hi) / 2;
        const en = entryName(mid);
        switch (std.mem.order(u8, name, en)) {
            .lt => hi = mid,
            .gt => lo = mid + 1,
            .eq => {
                const e = blob[dir_start + mid * entry_size ..][0..40];
                return .{ .offset = std.mem.readInt(u32, e[32..36], .little), .n = std.mem.readInt(u32, e[36..40], .little) };
            },
        }
    }
    return null;
}

fn rangesOf(e: Entry) []align(1) const Range {
    const p: [*]align(1) const Range = @ptrCast(blob[e.offset..].ptr);
    return p[0..e.n];
}

/// A property of strings (§22.2.2.9.7 table 68: `RGI_Emoji` and the six
/// emoji sequence sets it unites; `v` mode only): its single code points
/// as ranges, and its sequences as (n, n code points) records.
pub const StringProperty = struct {
    ranges: []align(1) const Range,
    words: []align(1) const u32,

    pub const Iterator = struct {
        words: []align(1) const u32,
        i: usize = 0,
        pub fn next(it: *Iterator) ?[]align(1) const u32 {
            if (it.i >= it.words.len) return null;
            const n = it.words[it.i];
            const s = it.words[it.i + 1 ..][0..n];
            it.i += 1 + n;
            return s;
        }
    };
    pub fn strings(p: StringProperty) Iterator {
        return .{ .words = p.words };
    }
};

pub fn stringProperty(name: []const u8) ?StringProperty {
    var buf: [40]u8 = undefined;
    if (name.len + 2 > buf.len) return null;
    @memcpy(buf[0..name.len], name);
    buf[name.len] = '/';
    buf[name.len + 1] = 'r';
    const r = find(buf[0 .. name.len + 2]) orelse return null;
    buf[name.len + 1] = 's';
    const s = find(buf[0 .. name.len + 2]) orelse return null;
    const words: [*]align(1) const u32 = @ptrCast(blob[s.offset..].ptr);
    return .{ .ranges = rangesOf(r), .words = words[0..s.n] };
}

/// A property table by the names ECMA-262 §22.2.2.9.7 accepts: a
/// binary property (`Alphabetic`, `AHex`, ...), a general category
/// value with or without `General_Category=`/`gc=`, or a script under
/// `Script=`/`sc=` / `Script_Extensions=`/`scx=`. Null when unknown.
pub fn property(name: []const u8, value: ?[]const u8) ?[]align(1) const Range {
    var buf: [48]u8 = undefined;
    if (value) |v| {
        const prefix: []const u8 = if (std.mem.eql(u8, name, "General_Category") or std.mem.eql(u8, name, "gc")) "gc=" else if (std.mem.eql(u8, name, "Script") or std.mem.eql(u8, name, "sc")) "sc=" else if (std.mem.eql(u8, name, "Script_Extensions") or std.mem.eql(u8, name, "scx")) "scx=" else return null;
        if (prefix.len + v.len > buf.len) return null;
        @memcpy(buf[0..prefix.len], prefix);
        @memcpy(buf[prefix.len .. prefix.len + v.len], v);
        return rangesOf(find(buf[0 .. prefix.len + v.len]) orelse return null);
    }
    // A lone name: a binary property, or a general category value.
    if (find(name)) |e| {
        // The case tables are not properties.
        if (std.mem.eql(u8, name, "fold") or std.mem.eql(u8, name, "upper") or std.mem.eql(u8, name, "lower") or std.mem.eql(u8, name, "upper_full") or std.mem.eql(u8, name, "lower_full")) return null;
        return rangesOf(e);
    }
    if (3 + name.len > buf.len) return null;
    @memcpy(buf[0..3], "gc=");
    @memcpy(buf[3 .. 3 + name.len], name);
    return rangesOf(find(buf[0 .. 3 + name.len]) orelse return null);
}

pub fn inRanges(ranges: []align(1) const Range, cp: u32) bool {
    var lo: usize = 0;
    var hi: usize = ranges.len;
    while (lo < hi) {
        const mid = (lo + hi) / 2;
        const r = ranges[mid];
        if (cp < r.lo) {
            hi = mid;
        } else if (cp > r.hi) {
            lo = mid + 1;
        } else return true;
    }
    return false;
}

fn has(name: []const u8, cp: u32) bool {
    const e = find(name) orelse return false;
    return inRanges(rangesOf(e), cp);
}

pub fn isIdStart(cp: u32) bool {
    if (cp < 128) return (cp >= 'a' and cp <= 'z') or (cp >= 'A' and cp <= 'Z') or cp == '$' or cp == '_';
    return has("ID_Start", cp);
}

pub fn isIdContinue(cp: u32) bool {
    if (cp < 128) return isIdStart(cp) or (cp >= '0' and cp <= '9');
    return has("ID_Continue", cp) or cp == 0x200c or cp == 0x200d;
}

pub fn isWhiteSpace(cp: u32) bool {
    return has("White_Space", cp);
}

/// A pair table lookup (from → to), or the code point itself.
fn mapped(name: []const u8, cp: u32) u32 {
    const e = find(name) orelse return cp;
    const pairs = rangesOf(e);
    var lo: usize = 0;
    var hi: usize = pairs.len;
    while (lo < hi) {
        const mid = (lo + hi) / 2;
        if (cp < pairs[mid].lo) {
            hi = mid;
        } else if (cp > pairs[mid].lo) {
            lo = mid + 1;
        } else return pairs[mid].hi;
    }
    return cp;
}

/// Simple case folding (CaseFolding.txt statuses C and S).
pub fn foldSimple(cp: u32) u32 {
    if (cp < 128) return if (cp >= 'A' and cp <= 'Z') cp + 32 else cp;
    return mapped("fold", cp);
}

pub fn toUpperSimple(cp: u32) u32 {
    if (cp < 128) return if (cp >= 'a' and cp <= 'z') cp - 32 else cp;
    return mapped("upper", cp);
}

pub fn toLowerSimple(cp: u32) u32 {
    if (cp < 128) return if (cp >= 'A' and cp <= 'Z') cp + 32 else cp;
    return mapped("lower", cp);
}

/// A full mapping (SpecialCasing's unconditional entries, then the
/// simple mapping): the code points, at most three, written to `out`.
pub fn toUpperFull(cp: u32, out: *[3]u32) usize {
    return fullMap("upper_full", toUpperSimple(cp), cp, out);
}

pub fn toLowerFull(cp: u32, out: *[3]u32) usize {
    return fullMap("lower_full", toLowerSimple(cp), cp, out);
}

fn fullMap(name: []const u8, simple: u32, cp: u32, out: *[3]u32) usize {
    if (cp >= 128) if (find(name)) |e| {
        const base = blob[e.offset..];
        var lo: usize = 0;
        var hi: usize = e.n;
        while (lo < hi) {
            const mid = (lo + hi) / 2;
            const rec = base[mid * 20 ..][0..20];
            const from = std.mem.readInt(u32, rec[0..4], .little);
            if (cp < from) {
                hi = mid;
            } else if (cp > from) {
                lo = mid + 1;
            } else {
                const n: usize = std.mem.readInt(u32, rec[4..8], .little);
                var i: usize = 0;
                while (i < n) : (i += 1) out[i] = std.mem.readInt(u32, rec[8 + i * 4 ..][0..4], .little);
                return n;
            }
        }
    };
    out[0] = simple;
    return 1;
}

test "unicode: properties, identifiers and case tables from the blob" {
    try std.testing.expect(isIdStart('a') and !isIdStart('1') and isIdStart(0x3b1) and !isIdStart(0x2028));
    try std.testing.expect(isIdContinue('1') and isIdContinue(0x300));
    try std.testing.expect(property("Lu", null) != null);
    try std.testing.expect(inRanges(property("Lu", null).?, 'A') and !inRanges(property("Lu", null).?, 'a'));
    try std.testing.expect(inRanges(property("Script", "Greek").?, 0x3b1));
    try std.testing.expect(inRanges(property("scx", "Latn").?, 0xb7));
    try std.testing.expect(inRanges(property("General_Category", "Nd").?, 0x660));
    try std.testing.expect(inRanges(property("L", null).?, 0x4e00));
    try std.testing.expect(inRanges(property("AHex", null).?, 'f') and !inRanges(property("AHex", null).?, 'g'));
    try std.testing.expect(property("Nope", null) == null);
    try std.testing.expectEqual(@as(u32, 's'), foldSimple(0x17f));
    try std.testing.expectEqual(@as(u32, 0x3c3), foldSimple(0x3c2));
    try std.testing.expectEqual(@as(u32, 0x1e9e), toUpperSimple(0xdf) + 0x1e9e - toUpperSimple(0xdf)); // ß has no simple upper mapping: stays ß
    var out: [3]u32 = undefined;
    try std.testing.expectEqual(@as(usize, 2), toUpperFull(0xdf, &out));
    try std.testing.expect(out[0] == 'S' and out[1] == 'S');
    try std.testing.expectEqual(@as(usize, 1), toLowerFull('A', &out));
    try std.testing.expectEqual(@as(u32, 'a'), out[0]);
}

test "unicode: properties of strings" {
    const rgi = stringProperty("RGI_Emoji").?;
    try std.testing.expect(inRanges(rgi.ranges, 0x231A)); // ⌚, a Basic_Emoji code point
    var it = rgi.strings();
    var n: usize = 0;
    var keycap = false;
    while (it.next()) |s| {
        n += 1;
        if (s.len == 3 and s[0] == '#' and s[1] == 0xFE0F and s[2] == 0x20E3) keycap = true;
    }
    try std.testing.expect(n > 2000);
    try std.testing.expect(keycap);
    try std.testing.expect(stringProperty("Emoji_Keycap_Sequence").?.ranges.len == 0);
    try std.testing.expect(stringProperty("Emoji") == null);
    try std.testing.expect(property("RGI_Emoji", null) == null);
}

test "unicode: Script=Unknown is the code points no script claims" {
    const unknown = property("Script", "Unknown").?;
    try std.testing.expect(inRanges(unknown, 0x0378)); // unassigned in Greek's block
    try std.testing.expect(!inRanges(unknown, 'a'));
    try std.testing.expect(!inRanges(unknown, 0x3000)); // Common
    try std.testing.expect(property("sc", "Zzzz") != null);
    try std.testing.expect(property("scx", "Unknown") != null);
}
