#!/usr/bin/env python3
"""Generate lib/web/entities.zig from the HTML Standard's entities.json
(https://html.spec.whatwg.org/entities.json): the named character
references, sorted by name, each with one or two code points.

    python3 tools/mkentities.py entities.json > lib/web/entities.zig
"""
import json, sys
d = json.load(open(sys.argv[1]))
names = sorted(k[1:] for k in d)  # without the leading '&'
print("//! The HTML Standard's named character references, generated by")
print("//! tools/mkentities.py from https://html.spec.whatwg.org/entities.json")
print("//! — %d names sorted for binary search, each one or two code points" % len(names))
print("//! (a second of 0 means one). Names that end in ';' are the modern")
print("//! ones; the %d without are the legacy forms the tokenizer accepts" % sum(1 for n in names if not n.endswith(';')))
print("//! unterminated, with the attribute-value exception. Do not edit.")
print("pub const Entry = struct { name: []const u8, cps: [2]u21 };")
print("pub const max_name_len = %d;" % max(len(n) for n in names))
print("pub const entries = [_]Entry{")
for n in names:
    cps = d['&' + n]['codepoints']
    a = cps[0]; b = cps[1] if len(cps) > 1 else 0
    print('    .{ .name = "%s", .cps = .{ 0x%x, 0x%x } },' % (n, a, b))
print("};")
