#!/usr/bin/env python3
"""Rasterize the kernel's console font: kernel/font/console8x16.zig.

The glyphs are Departure Mono (Helena Zhang, SIL Open Font License 1.1;
kernel/font/OFL-1.1.txt) at its native 12 px, which lands on an 8x16
pixel grid exactly — a pixel font, so no anti-aliasing is lost in the
threshold. Printable ASCII only (32..126). Needs Pillow with FreeType.

    python3 tools/mkfont.py /path/to/DepartureMono-Regular.otf > kernel/font/console8x16.zig
"""
import sys
from PIL import Image, ImageDraw, ImageFont

W, H, SIZE = 8, 16, 12
font = ImageFont.truetype(sys.argv[1], SIZE)
asc, desc = font.getmetrics()
top = (H - (asc + desc)) // 2

print("//! The console font: printable ASCII, 8x16, one byte per row, the")
print("//! high bit the leftmost pixel. Generated by tools/mkfont.py from")
print("//! Departure Mono 1.500 (Copyright 2022-2024 Helena Zhang), which is")
print("//! licensed under the SIL Open Font License 1.1 — see OFL-1.1.txt")
print("//! beside this file. This bitmap is a Modified Version under that")
print("//! license and is not named Departure Mono.")
print()
print("pub const width = %d;" % W)
print("pub const height = %d;" % H)
print("pub const first: u8 = 32;")
print("pub const last: u8 = 126;")
print("pub const glyphs = [_][%d]u8{" % H)
for code in range(32, 127):
    img = Image.new("L", (W, H), 0)
    ImageDraw.Draw(img).text((0, top), chr(code), font=font, fill=255)
    rows = []
    for y in range(H):
        bits = 0
        for x in range(W):
            if img.getpixel((x, y)) >= 110:
                bits |= 0x80 >> x
        rows.append(bits)
    name = chr(code) if code != 92 else "backslash"
    print("    // %-9s %s" % (repr(name) if code != 32 else "space", ""))
    print("    .{ " + ", ".join("0x%02x" % r for r in rows) + " },")
print("};")
